### ISSUE TITLE
chunk-nordic can use HTTP Tunneling via GET method ?

### ISSUE THREAD

**Issue by ingnelson** [Snawoot/chunk-nordic#5]
Hello.

chunk-nordic can use HTTP Tunneling via GET method ?

becuase my firewall blocks my connections when the HTTP request beging with a CONNECT method.

If the answer is yes : what is the command to run the server .

I will wait your answer.

**Comment by Snawoot** [comment]
Hi!

Client site uses POST method both for upstream and downstream connection.

**Comment by ingnelson** [comment]
@Snawoot Could you create a Android app to use it as a client , please ? 
Because in many countres it is the only way to connect to internet via a HTTP tunnel using GET or POST or DELETE or HEAD methods .

can you do it , please ?

**Comment by Snawoot** [comment]
No, I'm not familiar with mobile development and I have no plans for it.

I guess you are better off with shadowsocks + v2ray plugin which has nice mobile applications. By the way, in which country you have such restrictions?

**Comment by ingnelson** [comment]
@Snawoot  This restrictions are in this countries : Brasil , Central-America and Mexico .

The problem with shadowsocks + v2ray plugin it is those app i can not modify the HTTP request .

I need to send a HTTP request different than like shadowsocks send it.

The connection i am trying to create is : 
`HTTP request on port 80 > Shadowsocks on port 443  > internet > HTTP server listen on port 80 > shadowsocks server listen on port 443 `

The http request goes to shadowsocks via localhost (example: 127.0.0.1:4242) , so shadowsocks obfuscate the data .

I need to modify the last HTTP Header similar like this :



```
GET #0=fown&method=1&down=15000# HTTP/1.1\r\n ٌُُُُُُّّّّْْْْْْْْْْْْْْْْْْ\r\n\r\n
```

As you can see this http request do not finish with `\r\n\r\n` , it finish with `\r\n ٌُُُُُُّّّّْْْْْْْْْْْْْْْْْْ\r\n\r\n` this has NON-ASCII characters after the first `\r\n`  +` space` , this NON-ASCII character is the trick to bypass the firewall.

On wireshark program the connection looks like this : 

![4Full_request_and_response](https://user-images.githubusercontent.com/6626845/87883689-406fd580-c9c6-11ea-9417-dc0aacc2bc18.jpg)
![1HTTP REQUEST](https://user-images.githubusercontent.com/6626845/87883694-42399900-c9c6-11ea-9474-0e257b96925c.jpg)
![2NON-ASCII CHARACTERS](https://user-images.githubusercontent.com/6626845/87883697-449bf300-c9c6-11ea-9ba9-99fbfebe79cb.jpg)
![3HTTP RESPONSE](https://user-images.githubusercontent.com/6626845/87883702-4665b680-c9c6-11ea-896f-e29ac19352b7.jpg)


I am not a programmer , but i just tried to create a server file on python that works as a told you before ,  can you check it and modify or edit my server script to make it works ?

https://github.com/ingnelson/proxy-ascii
