### ISSUE TITLE
Unable to create multiple tunnels over two machines

### ISSUE THREAD

**Issue by roointan** [Snawoot/chunk-nordic#7]
This works perfectly well, when a single tunnel is created over two machines (I use it to pass OpenVPN traffic through, to bypass DPI)
But when I start a second tunnel, both connections keep connecting, and disconnecting. Seems they can't both stay connected.
Is there a solution for this?

**Comment by Snawoot** [comment]
Hi! Shouldn't be happening, sessions have separate UUID and traffic does not mix anyhow. Maybe your openvpn config uses same username or CN for both instances and OpenVPN server just dropping one? Anyway, please post application logs from both sides covering period when this is happening.

**Comment by roointan** [comment]
Hello and thanks for answering and being available!
hmm, I've used multiple configs, and multiple VPN connections using other methods without problem (like over reverse ssh port forwarding.) But I'll test again being more careful with conditions.
I'll post logs some time later.

**Comment by roointan** [comment]
Hi again. You wanted Openvpn logs, right? Or do you want chunk-nordic logs?
Here are logs from Openvpn clients:
[iPhone-OpenVPN.txt](https://github.com/Snawoot/chunk-nordic/files/10716349/iPhone-OpenVPN.txt)
[mac-tunnelblick.txt](https://github.com/Snawoot/chunk-nordic/files/10716350/mac-tunnelblick.txt)

**Comment by Snawoot** [comment]
Thank you! Would be nice to have both.

**Comment by roointan** [comment]
logs of chunk-nordic servers and clients.
[client1.log](https://github.com/Snawoot/chunk-nordic/files/10723260/client1.log)
[client2.log](https://github.com/Snawoot/chunk-nordic/files/10723261/client2.log)
[server1.log](https://github.com/Snawoot/chunk-nordic/files/10723262/server1.log)
[server2.log](https://github.com/Snawoot/chunk-nordic/files/10723263/server2.log)

**Comment by Snawoot** [comment]
@roointan Thank you!

**Comment by Snawoot** [comment]
Problem didn't appeared on my local tests: server and client handling multiple connections well. Probably there is some limitation on connection number which from from your DPI/censorship appliances.

**Comment by roointan** [comment]
Thanks for taking your time.
